name: flutter_context_menu_web
description: A new Flutter project.

version: 1.0.0+1

flutter:
  plugin:
    platforms:
      web:
        pluginClass: ContextMenuPlugin
        fileName: context_menu_plugin.dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
